### PR TITLE
Added partyHard Rager Mode Test

### PR DESCRIPTION
**Pull request by rinc3w1nd**
Thought this might be fun, but I have no idea what bulbs are in teh streetlight, so may be a bit aggressive with timing.

### CODE REVIEW

**Comment by magikid** [comment]
This looks fun but I don't think that it should be put into the main server script.  I feel like this would be better as a standalone script that took advantage of the REST API.  As this is currently written, there is no way to exit rager mode without resetting the Pi.

**Comment by rinc3w1nd** [comment]
Exit no, but it terminates after 5 iterations in current form

**Comment by rinc3w1nd** [comment]
iterations, max_iterations, prev = 0, 5, 0
+    while True:
+        if iterations < max_iterations: iterations = iterations + 1
+        else: break

**Comment by magikid** [comment]
Oops, I guess it does exit on its own.  Python isn't my usual language.  I think my other point still stands that this would be better suited as its own script instead of being incorporated into the server script.

Why should this be its own API endpoint?

**Comment by rinc3w1nd** [comment]
6 vs ½ dozen. I wrote it one night because I was bored. What you guys decide to do with it is up to you. Haven't even seen the interface for the streetlight in the space yet anyway...

As an aside, one thought though for further development of the light's function would be to tie in to scheduling for the space so the key holder could shift yellow at 30 mins to close, red at 10, and aggregate that info to the web so people are aware when the space is closing instead of just open/closed...

**Comment by magikid** [comment]
Thanks for the idea!  I've opened it up as an issue.

**Comment by flayisflay** [comment]
I ACCEPT THIS WITHOUT COMPUNCTION.

**Pull request merged**
